os:
- linux
- osx

env:
  global:
  - secure: jrAuM2d8/Pu83cps6cIzoZl/uOcz3cd53Sb/16kWujrb03dKFn+avOSRapOqU9eYMRIMi75fYsKc0rK4UHGRoCBmYLMHVZdZJvlcVxLqIF/+CQjwvYCezyoRLW5POIuTcJr/jGOuoilYQgx56Dv97ZIndeczZocAk3u2glcpT64=
  matrix:
  - PYTHON_VERSION=2
  - PYTHON_VERSION=3

matrix:
  allow_failures:
  - env: PYTHON_VERSION=3

install:
- wget https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py -O traviconda.py
- export MENPO_VERSION=$(python traviconda.py version)
- python traviconda.py setup $PYTHON_VERSION --channel menpo
- export PATH="$HOME/miniconda/bin:$PATH"

script:
- python traviconda.py auto ./conda --binstaruser menpo --binstarkey $BINSTAR_KEY --pypiuser $PYPI_USERNAME  --pypipassword $PYPI_PASSWORD

notifications:
  email: false
  flowdock: 769202b66114a5ce0e61df484dfeb177
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
